/* PhD Monash workspace. Notes are a dated snapshot; checkpoint data stays on this browser. */
'use strict';
const $ = id => document.getElementById(id);
const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const STORAGE = 'pathways.phd.monash.v1';
const SECTIONS = [['overview','◫','Ringkasan'],['concept','⌘','Concept map'],['plan','↗','Research plan'],['literature','▤','Referensi literatur'],['methods','⊞','Metode & data'],['analysis','◉','Equity & spasial'],['weekly','✓','Checkpoint mingguan'],['notes','▧','Catatan Obsidian']];
const RQS = [
 {id:'RQ1',name:'Distribute',kind:'INTI · NASIONAL',desc:'Siapa yang terlayani, dan bagaimana akses berbeda menurut kebutuhan, kesejahteraan, serta urban–rural?',note:'RQ1 Distribute',scope:'Distribusi & aksesibilitas'},
 {id:'RQ2',name:'Perceive',kind:'INTI · PENGALAMAN',desc:'Hambatan keandalan dan akses apa yang dilaporkan pengguna melalui ulasan?',note:'RQ2 Perceive',scope:'Ulasan & klasifikasi teks'},
 {id:'RQ3',name:'Integrate',kind:'PENGHUBUNG · JABAR',desc:'Apakah cakupan di peta sejalan dengan layanan yang tersedia dan pengalaman pengguna?',note:'RQ3 Integrate',scope:'Coverage × usable access'},
 {id:'RQ4',name:'Redefine',kind:'PENGEMBANGAN',desc:'Seberapa jauh penilaian keadilan berubah ketika definisi kebutuhan diganti?',note:'RQ4 Redefine',scope:'Kebutuhan & sensitivitas'}
];
const WORK = [
 ['w1','Minggu 1','Audit & satukan data','Rekonsiliasi lokasi, charger, port, periode dan filter operator.','Register data acuan + daftar selisih angka.'],
 ['w2','Minggu 2','Kunci protokol penelitian','Tetapkan outcome, unit, bobot, ranking sosial ekonomi dan standar keadilan.','Protokol dua halaman + keputusan untuk pembimbing.'],
 ['w3','Minggu 3','Pilot akses & indeks','Uji Gini/CI dengan kasus sederhana; bangun tabel wilayah dan akses.','Pilot yang dapat dijalankan ulang, termasuk wilayah akses nol.'],
 ['w4','Minggu 4','Sensitivitas & memo pilot','Bandingkan definisi akses/kebutuhan dan periksa mutu data.','Memo 3–5 halaman, peta, tabel sensitivitas dan batas bukti.'],
 ['w5','Minggu 5','Anotasi & literatur terarah','Uji codebook ulasan, anotasi ganda sebagian sampel, petakan literatur ke keputusan.','Label yang dievaluasi + matriks literatur.'],
 ['w6','Minggu 6','Baseline nasional & persepsi','Perluas analisis yang lolos pilot; evaluasi klasifikasi dengan data uji terpisah.','Draf hasil RQ1 dan evaluasi RQ2.'],
 ['w7','Minggu 7','Hubungkan akses & pengalaman','Selaraskan unit dan periode untuk membandingkan coverage dengan usability.','Peta kuadran dan penjelasan sesuai/tidak sesuainya hasil.'],
 ['w8','Minggu 8','Sintesis & bahan supervisi','Tulis implikasi, ketidakpastian, keputusan metode dan pekerjaan berikutnya.','Draf terintegrasi + keputusan lingkup bersama pembimbing.']
];
let corpus = {notes:[]}, state = {version:1,entries:[],completed:[]}, storageOK = true, currentNote = null, readerHistory = [], editing = null;
const noteByTitle = title => corpus.notes.find(n => n.title === title || n.path.replace(/\.md$/,'') === title);
function toast(message) { $('toast').textContent=message;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',4200); }
function validEntry(e) {
 return e && typeof e.id==='string' && e.id.length<100 && /^\d{4}-\d{2}-\d{2}$/.test(e.week) && !Number.isNaN(Date.parse(e.week)) && ['planned','progress','done','blocked'].includes(e.status) && ['RQ1','RQ2','RQ3','RQ4','Lintas RQ'].includes(e.rq) && Number.isFinite(e.progress) && e.progress>=0 && e.progress<=100 && ['target','achieved','evidence','blockers','next','supervisor'].every(k=>typeof e[k]==='string' && e[k].length<=10000);
}
function validateState(data) {
 if (!data || data.version!==1 || !Array.isArray(data.entries) || !Array.isArray(data.completed) || data.entries.length>2000 || !data.entries.every(validEntry) || !data.completed.every(x=>WORK.some(w=>w[0]===x))) throw new Error('Format cadangan tidak sesuai. Gunakan berkas ekspor PhD Monash.');
 if(new Set(data.entries.map(e=>e.id)).size!==data.entries.length || new Set(data.entries.map(e=>e.week)).size!==data.entries.length) throw new Error('Cadangan memiliki minggu atau ID ganda.');
 return {version:1,entries:data.entries.map(e=>({...e})),completed:[...new Set(data.completed)]};
}
function loadState() {
 try { const raw=localStorage.getItem(STORAGE);if(raw)state=validateState(JSON.parse(raw)); }
 catch(error) {storageOK=false;toast('Catatan browser belum dapat dibaca. Ekspor cadangan sebelum menghapus data browser.');}
}
function saveState(next) {
 try {localStorage.setItem(STORAGE,JSON.stringify(next));state=next;storageOK=true;return true;}
 catch(error) {storageOK=false;toast('Penyimpanan gagal. Isian tetap terbuka; periksa izin atau ruang penyimpanan browser.');return false;}
}
function download(name,content,type='application/json') {const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),5000);}
function sourceButton(title,label='Baca catatan sumber') {return `<button class="secondary" data-note="${esc(title)}">${esc(label)} ↗</button>`;}
function head(kicker,title,desc) {return `<div class="page-head"><span class="eyebrow">${kicker}</span><h1>${title}</h1><p>${desc}</p></div>`;}
function rqCards() {return RQS.map((r,i)=>`<button class="rq-card" data-note="${r.note}"><span class="pill ${i===1?'blue':i===3?'gold':''}">${r.id} · ${r.kind}</span><h3>${r.name}</h3><p>${r.desc}</p><div class="foot">${r.scope} ↗</div></button>`).join('');}
function overview() {
 const done=state.entries.filter(e=>e.status==='done').length;
 return `<section class="hero"><div><span class="eyebrow">MONASH UNIVERSITY · RACE FOR 2030</span><h1>Memahami akses.<br><em>Menguji keadilan.</em></h1><p>Ruang kerja PhD untuk menyatukan pertanyaan, bacaan, data, dan langkah penelitian tentang infrastruktur pengisian EV di Indonesia.</p><div class="hero-buttons"><a class="primary" href="#weekly">+ Checkpoint minggu ini</a><a class="secondary" href="#concept">Jelajahi concept map ↗</a></div></div><div class="hero-graphic"><span class="eyebrow">PERTANYAAN PUSAT</span><div class="big">Siapa yang<br>benar-benar<br>terlayani?</div><small>Akses · kebutuhan · pengalaman</small></div></section>
 <div class="stats"><div class="stat"><span class="label">PERTANYAAN PENELITIAN</span><strong>04</strong><small>Dua inti, integrasi, pengembangan</small></div><div class="stat"><span class="label">CATATAN LITERATUR</span><strong>${corpus.notes.filter(n=>n.group==='Literatur').length}</strong><small>Terhubung dengan Obsidian</small></div><div class="stat"><span class="label">CHECKPOINT TERCATAT</span><strong>${String(state.entries.length).padStart(2,'0')}</strong><small>${done} minggu berstatus selesai</small></div><div class="stat"><span class="label">PAKET KERJA SELESAI</span><strong>${state.completed.length}<span style="font-size:16px;color:var(--muted)"> / 8</span></strong><small>Berdasarkan entri Anda</small></div></div>
 <div class="section-title"><h2>Empat pertanyaan, satu arah penelitian</h2><a href="#plan">Lihat research plan →</a></div><div class="rq-grid">${rqCards()}</div>
 <div class="two-col"><section class="panel"><h2>Langkah terdekat</h2>${WORK.filter(w=>!state.completed.includes(w[0])).slice(0,3).map(w=>`<div class="task-row"><span class="task-num">${w[0].slice(1).padStart(2,'0')}</span><div><strong>${w[2]}</strong><small>${w[4]}</small></div></div>`).join('')||'<p>Delapan paket telah ditandai selesai. Catat sintesis dan keputusan berikutnya.</p>'}<a class="text-link" href="#plan">Atur checkpoint pekerjaan →</a></section><section class="panel"><span class="eyebrow">CATATAN UNTUK SUPERVISI</span><h2 style="margin-top:14px">Dari dashboard ke bukti riset</h2><p>Pisahkan jangkauan 10 km dari waktu perjalanan 10 menit, peringkat IPM dari pendapatan, dan jumlah charger dari akses yang dialami penduduk.</p>${sourceButton('Rencana penyelesaian riset GeoSPKLU','Buka rencana & audit metode')}<div class="source-note">Pembimbing dalam catatan: Alyas Widita · Liz Taylor.<br>Milestone formal mengikuti kesepakatan program.</div></section></div><div class="source-note">Snapshot ${esc(corpus.source)} · ${esc(corpus.importedAt)} · ${corpus.notes.length} catatan riset. Pembaruan Obsidian berikutnya perlu diimpor ulang.</div>`;
}
function concept() {
 const node=(title,sub,note,cls='')=>`<button class="flow-node ${cls}" data-note="${esc(note)}"><b>${title}</b><span>${sub}</span></button>`;
 return head('KERANGKA KONSEPTUAL','Satu peta, empat pertanyaan.','Klik sebuah simpul untuk membuka catatan sumber. Hubungan ini adalah kerangka analisis; arah panah tidak menyatakan sebab-akibat yang sudah terbukti.')+
 `<div class="flow"><div class="flow-row">${node('Standar keadilan','Siapa diprioritaskan? Apa akses minimum?','Distributive justice')}${node('Kebutuhan pengisian','Penduduk · perjalanan · EV · home charging','07 Redefining Need')}</div><div class="arrow">↓ tolok ukur dan dasar pembanding</div><div class="flow-row">${node('RQ1 · Distribute','Lokasi + kapasitas + jangkauan → pola akses','RQ1 Distribute','dark')}${node('RQ2 · Perceive','Ulasan + anotasi → hambatan yang dirasakan','RQ2 Perceive','dark')}</div><div class="arrow">↓ pola cakupan + pengalaman pengguna + bukti operasional</div><div class="flow-row">${node('RQ3 · Integrate','Apakah coverage berarti akses yang bisa digunakan?','RQ3 Integrate','dark')}</div><div class="arrow">↓ nilai kesesuaian · periksa perbedaan</div><div class="flow-row">${node('Kesenjangan akses','Wilayah dan kelompok mana yang kurang terlayani?','29 Peta Konsep Penelitian SPKLU')}${node('RQ4 · Redefine ↺','Uji ulang definisi kebutuhan dan kestabilan kesimpulan','RQ4 Redefine','dashed')}</div><div class="arrow">↓ dasar pembahasan kebijakan</div><div class="flow-row">${node('Lokasi · mutu layanan · prioritas','Intervensi mengikuti jenis hambatan yang ditemukan.','29 Peta Konsep Penelitian SPKLU')}</div></div><p class="flow-caption">RQ4 menguji kembali kebutuhan dan kesenjangan akses. Garis putus-putus menandai pengembangan bersyarat.</p>
 <div class="two-col"><section class="panel"><h2>Access gap sebagai konsep pemersatu</h2><p>Bandingkan target dan akses terukur pada unit serta periode yang sama. Jangan mengurangkan jumlah penduduk, kWh, jumlah charger, dan skor persepsi yang berbeda satuan.</p>${sourceButton('29 Peta Konsep Penelitian SPKLU')}</section><section class="panel"><h2>Umpan balik yang perlu diuji</h2><p>Lokasi dibangun → transaksi teramati → estimasi kebutuhan → lokasi berikutnya. Ini kandidat mekanisme, bukan temuan kausal yang sudah terbukti.</p>${sourceButton('Selection bias (censored demand)')}</section></div>`;
}
function plan() {return head('RESEARCH PLAN','Dari pertanyaan ke hasil yang bisa diuji.','Rencana delapan paket kerja, diturunkan dari agenda bimbingan dan rencana GeoSPKLU. Minggu dihitung relatif sejak pelaksanaan; sesuaikan dengan kesiapan data dan kesepakatan pembimbing.')+
 `<div class="toolbar">${sourceButton('00 Project Brief','Brief penelitian')}${sourceButton('32 Agenda Bimbingan Bulan Ketiga dan Milestone','Agenda bimbingan')}${sourceButton('Rencana penyelesaian riset GeoSPKLU','Rencana lengkap')}</div><div class="notice">Jadwal ini adalah usulan kerja, bukan tenggat resmi confirmation Monash. Penomoran RQ mengikuti peta konsep terbaru di Obsidian; sebagian manuskrip lama memakai susunan berbeda.</div><section class="panel" style="margin-bottom:20px"><div class="section-title" style="margin:0"><h2>${state.completed.length} dari 8 paket ditandai selesai</h2><span class="field-help">Progres paket kerja, bukan persentase disertasi</span></div><div class="progress-track"><span style="width:${state.completed.length/8*100}%"></span></div></section><div class="timeline">${WORK.map(w=>`<div class="timeline-item"><div class="week">${w[1]}</div><div><h3>${w[2]}</h3><p>${w[3]}<br><strong>Keluaran:</strong> ${w[4]}</p></div><label title="Tandai ${w[2]} selesai"><input type="checkbox" data-work="${w[0]}" ${state.completed.includes(w[0])?'checked':''} aria-label="${w[2]} selesai"></label></div>`).join('')}</div><div class="two-col"><section class="panel"><h2>Inti & integrasi</h2><p>RQ1 distribusi nasional dan RQ2 persepsi menjawab brief. RQ3 menyatukan keduanya menggunakan bukti operasional yang dapat divalidasi.</p>${sourceButton('21 Kenapa Empat RQ')}</section><section class="panel"><h2>Pengembangan bersyarat</h2><p>Riwayat pembukaan, kebutuhan alternatif, dan inferensi kausal diteruskan jika data serta desain memadai. Tetapkan batas lingkup bersama pembimbing.</p>${sourceButton('09 Timeline','Timeline Obsidian')}</section></div>`;}
function noteCards(notes) {return notes.map(n=>`<button class="note-card" data-note-id="${n.id}"><span class="pill">${esc(n.group)}</span><h3>${esc(n.title)}</h3><p>${esc(n.summary)}</p><span class="read">Baca catatan →</span></button>`).join('')||'<div class="empty">Tidak ada catatan yang cocok. Coba kata kunci lain.</div>';}
function library(literature=false) {
 const notes=corpus.notes.filter(n=>!literature||n.group==='Literatur');
 return head(literature?'LITERATURE REVIEW':'OBSIDIAN → PHD',literature?'Bacaan yang menopang keputusan.':'Catatan riset, dalam satu tempat.',literature?'Telusuri ringkasan, konsep, kaitan ke RQ, dan tautan sumber yang tersimpan di Obsidian. Status bacaan mengikuti catatan sumber; keberadaan ringkasan tidak otomatis berarti paper selesai diverifikasi.':'Snapshot catatan inti, research questions, konsep, latihan, dan literatur. Tautan antarcatatan tetap bisa dibuka; PDF serta aset gambar tidak disalin dalam snapshot teks ini.')+
 `<div class="toolbar"><input type="search" id="note-search" aria-label="Cari catatan" placeholder="Cari judul, konsep, metode, atau RQ…">${literature?'<select id="note-filter" aria-label="Filter research question"><option value="">Semua RQ</option><option>RQ1</option><option>RQ2</option><option>RQ3</option><option>RQ4</option></select>':'<select id="note-filter" aria-label="Filter kategori"><option value="">Semua kategori</option>'+[...new Set(corpus.notes.map(n=>n.group))].map(g=>`<option>${esc(g)}</option>`).join('')+'</select>'}</div><div class="result-count" id="result-count">${notes.length} catatan</div><div id="note-results" class="note-grid">${noteCards(notes)}</div>`;
}
function methods() {
 const items=[['01','Audit & unit analisis','Master lokasi, port simultan, operator, penduduk, periode, dan kode wilayah. Missing dibedakan dari akses nol.','13 Data & Aset Empiris'],['02','Aksesibilitas spasial','Baseline repo: radius garis lurus 10 km. Tahap lanjutan: routing jalan dan kapasitas/kompetisi melalui E2SFCA.','Accessibility'],['03','Gini · concentration index','Gini mengukur besar ketimpangan. CI memakai ranking kesejahteraan yang disebut jelas; IPM tidak sama dengan pendapatan.','Rencana penyelesaian riset GeoSPKLU'],['04','Persepsi & kualitas label','Anotasi manual, pemeriksaan antarpenilai, baseline klasifikasi dan evaluasi per kelas; hindari kebocoran antarstasiun.','RQ2 Perceive'],['05','Coverage × usability','Selaraskan unit dan waktu. Uji apakah cakupan sejalan dengan layanan; jeda transaksi bukan ukuran downtime langsung.','RQ3 Integrate'],['06','Sensitivitas & inferensi','Bandingkan definisi kebutuhan, ranking, threshold dan skala. Analisis kausal memerlukan pembanding serta asumsi tambahan.','Threats to validity']];
 return head('METHODS & EVIDENCE','Metode mengikuti pertanyaan.','Rangkaian kerja menghubungkan standar keadilan, ukuran akses, kualitas data, dan batas kesimpulan.')+`<div class="method-grid">${items.map(i=>`<section class="method-card"><span class="pill">LANGKAH ${i[0]}</span><h3>${i[1]}</h3><p>${i[2]}</p>${sourceButton(i[3])}</section>`).join('')}</div><div class="notice">Protokol Obsidian memuat pilihan metode yang masih berupa draf. Koreksi Erreygers tidak otomatis diperlukan hanya karena nilai nonnegatif atau miring; hasil tidak signifikan juga tidak membuktikan pemerataan. Ambang akses dan pengukuran antrean perlu validasi.</div><div class="toolbar">${sourceButton('20 Protokol Analisis','Protokol sumber')}${sourceButton('11 Evidence Ledger','Evidence ledger')}${sourceButton('12 Decision Log','Decision log')}</div>`;
}
function analysis() {
 const tabs=[['equity','◐','Spatial Equity','Distribusi unit, konsumsi, Lorenz dan concentration index pada data regional.'],['keadilan','⚖','Ekuitas vs Kesetaraan','Gini, Theil, konsentrasi sosial ekonomi, dinamika, dan skenario kebijakan.'],['ekuitas','◇','Peta Ekuitas','Jangkauan nasional, kelompok kurang terlayani, dan kelayakan jaringan.'],['socio','▥','Socio-Economic','Indikator wilayah sebagai konteks distribusi dan peringkat sosial ekonomi.'],['perception','◎','Perception','Keluhan, aspek layanan, dan persepsi pengguna dari ulasan.']];
 return head('EQUITY & SPATIAL ANALYSIS','Analisis empiris untuk PhD.','Kelima modul ini sekarang berada di grup PhD Monash pada dashboard. Buka modul untuk menggunakan filter, peta, dan hasil analisis yang sudah tersedia.')+`<div class="note-grid">${tabs.map(t=>`<a class="analysis-card" href="../index.html#tab=${t[0]}" target="_top"><span class="symbol">${t[1]}</span><h3>${t[2]}</h3><p>${t[3]}</p><small>Buka modul analisis ↗</small></a>`).join('')}</div><div class="notice">Baca metode sebelum memakai angka sebagai temuan: 10 km ≠ 10 menit; IPM ≠ pendapatan; kota/kabupaten ≠ urban–rural. Beberapa angka naskah dan hitung ulang masih memerlukan rekonsiliasi.</div>${sourceButton('Rencana penyelesaian riset GeoSPKLU','Lihat audit & prioritas analisis')}`;
}
function monday() {const d=new Date();d.setDate(d.getDate()-((d.getDay()+6)%7));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function dateLabel(s) {return new Date(s+'T12:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'long',year:'numeric'});}
const STATUS={planned:'Direncanakan',progress:'Berjalan',done:'Selesai',blocked:'Terhambat'};
function weekly() {
 const entry=state.entries.find(e=>e.id===editing)||{week:monday(),rq:'Lintas RQ',status:'progress',progress:0,target:'',achieved:'',evidence:'',blockers:'',next:'',supervisor:''};
 return head('WEEKLY CHECKPOINT','Sedikit demi sedikit, tercatat.','Catat target, hasil, bukti, hambatan, dan keputusan bimbingan. Satu catatan per minggu membantu Anda melihat perkembangan yang benar-benar terjadi.')+
 `<div class="storage-note">Entri tersimpan <strong>di browser dan alamat situs ini</strong>, belum tersinkron lintas perangkat. Ekspor JSON untuk cadangan atau pindah dari preview ke situs utama. ${storageOK?'':'<strong class="error">Penyimpanan perlu diperiksa.</strong>'}</div><div class="toolbar" style="margin-top:15px"><button class="secondary" id="export-json">↓ Ekspor cadangan JSON</button><button class="secondary" id="export-md">↓ Ringkasan Markdown</button><button class="secondary" id="import-json">↑ Impor cadangan</button><input type="file" id="import-file" accept="application/json,.json" hidden></div>
 <section class="panel"><h2>${editing?'Edit checkpoint':'Checkpoint baru'}</h2><form id="weekly-form"><div class="form-grid"><label>Minggu dimulai<input type="date" name="week" value="${esc(entry.week)}" required><span class="field-help">Tanggal dinormalisasi ke hari Senin pada minggu yang dipilih.</span></label><label>Fokus penelitian<select name="rq">${['Lintas RQ','RQ1','RQ2','RQ3','RQ4'].map(v=>`<option ${v===entry.rq?'selected':''}>${v}</option>`).join('')}</select></label><label>Status<select name="status">${Object.entries(STATUS).map(([k,v])=>`<option value="${k}" ${k===entry.status?'selected':''}>${v}</option>`).join('')}</select></label><label>Capaian target minggu ini (%)<input type="number" name="progress" min="0" max="100" value="${entry.progress}" required><span class="field-help">Penilaian pribadi atas target minggu ini, bukan progres keseluruhan PhD.</span></label>${[['target','Target minggu ini','Contoh: satukan definisi lokasi, unit, dan port.'],['achieved','Hasil yang dikerjakan','Tuliskan hasil, termasuk temuan negatif atau perubahan arah.'],['evidence','Bukti / tautan keluaran','Nama berkas, tautan repo, tabel, peta, atau memo.'],['blockers','Hambatan & kebutuhan bantuan','Data, metode, waktu, atau keputusan yang belum tersedia.'],['next','Langkah minggu berikutnya','Satu sampai tiga pekerjaan yang konkret.'],['supervisor','Catatan / keputusan supervisi','Bedakan usulan Anda dari keputusan yang disepakati.']].map(([name,label,placeholder])=>`<label ${name==='target'?'class="full"':''}>${label}<textarea name="${name}" maxlength="10000" placeholder="${placeholder}" ${name==='target'?'required':''}>${esc(entry[name])}</textarea></label>`).join('')}</div><div class="form-actions"><button type="submit" class="primary">${editing?'Simpan perubahan':'Simpan checkpoint'}</button>${editing?'<button type="button" id="cancel-edit" class="secondary">Batal edit</button>':''}</div></form></section>
 <section class="history"><div class="section-title"><h2>Riwayat mingguan</h2><span class="field-help">${state.entries.length} checkpoint</span></div>${[...state.entries].sort((a,b)=>b.week.localeCompare(a.week)).map(e=>`<article class="entry"><div class="entry-head"><h3>Minggu ${dateLabel(e.week)} · ${esc(e.rq)}</h3><span class="pill ${e.status==='blocked'?'gold':''}">${STATUS[e.status]} · ${e.progress}% target minggu</span></div><p><strong>Target:</strong> ${esc(e.target)}</p>${[['achieved','Hasil'],['evidence','Bukti'],['blockers','Hambatan'],['next','Berikutnya'],['supervisor','Supervisi']].filter(([k])=>e[k]).map(([k,label])=>`<p><strong>${label}:</strong> ${esc(e[k])}</p>`).join('')}<div class="entry-actions"><button class="secondary" data-edit="${esc(e.id)}">Edit</button><button class="secondary danger" data-delete="${esc(e.id)}">Hapus</button></div></article>`).join('')||'<div class="empty">Belum ada checkpoint. Mulai dari satu target dan hasil minggu ini.</div>'}</section>`;
}
function safeURL(raw) {try {const u=new URL(raw);return ['https:','http:'].includes(u.protocol)?u.href:null;}catch{return null;}}
function inline(raw) {
 const tokens=[];const token=html=>{tokens.push(html);return `\u0000${tokens.length-1}\u0000`;};
 let s=raw.replace(/!\[\[([^\]]+)\]\]/g,(_,p)=>token(`<em>Aset sumber: ${esc(p)}</em>`)).replace(/\[\[([^\]]+)\]\]/g,(_,p)=>{const [target,label]=p.split('|');return token(`<button class="wiki" data-note="${esc(target.split('#')[0])}">${esc(label||target)}</button>`);}).replace(/!?\[([^\]]+)\]\(([^)]+)\)/g,(_,label,url)=>{const safe=safeURL(url);return token(safe?`<a href="${esc(safe)}" target="_blank" rel="noopener noreferrer">${esc(label)}</a>`:esc(label));});
 s=esc(s).replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>');return s.replace(/\u0000(\d+)\u0000/g,(_,i)=>tokens[Number(i)]||'');
}
function markdown(text) {
 const lines=text.split('\n');let out='',inCode=false,code=[],lang='',list=false;
 const endList=()=>{if(list){out+='</ul>';list=false;}};
 for(let i=0;i<lines.length;i++) {const line=lines[i];
  if(line.startsWith('```')) {endList();if(inCode){out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;if(lang==='mermaid')out+='<p class="field-help">Diagram sumber. Peta interaktif tersedia pada menu Concept map.</p>';code=[];}else lang=line.slice(3).trim();inCode=!inCode;continue;}
  if(inCode){code.push(line);continue;}
  if(line.startsWith('|')&&lines[i+1]&&/^\|[\s:|-]+\|\s*$/.test(lines[i+1])){endList();const cells=l=>l.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim());out+='<div class="table-scroll"><table><thead><tr>'+cells(line).map(x=>`<th>${inline(x)}</th>`).join('')+'</tr></thead><tbody>';i++;while(lines[i+1]?.startsWith('|')){i++;out+='<tr>'+cells(lines[i]).map(x=>`<td>${inline(x)}</td>`).join('')+'</tr>';}out+='</tbody></table></div>';continue;}
  const h=line.match(/^(#{1,6})\s+(.+)/);if(h){endList();out+=`<h${h[1].length}>${inline(h[2])}</h${h[1].length}>`;continue;}
  if(/^\s*[-*]\s+|^\s*\d+\.\s+/.test(line)){if(!list){out+='<ul>';list=true;}out+=`<li>${inline(line.replace(/^\s*(?:[-*]|\d+\.)\s+/,''))}</li>`;continue;}
  endList();if(line.startsWith('>'))out+=`<blockquote>${inline(line.replace(/^>\s?/,''))}</blockquote>`;else if(line==='---')out+='<hr>';else if(line.trim())out+=`<p>${inline(line)}</p>`;
 }
 endList();if(inCode)out+=`<pre><code>${esc(code.join('\n'))}</code></pre>`;return out;
}
function openNote(note,back=false) {
 if(!note){toast('Catatan atau aset ini belum termasuk snapshot teks. Buka sumber di Obsidian.');return;}
 if(currentNote&&$('reader').open&&!back)readerHistory.push(currentNote);
 currentNote=note;$('reader-title').textContent=note.title;$('reader-group').textContent=note.group;
 $('reader-meta').innerHTML=(readerHistory.length?'<button id="reader-back" class="back-note">← Catatan sebelumnya</button>':'')+esc(note.path)+' · Snapshot '+esc(corpus.importedAt);
 $('reader-body').innerHTML=markdown(note.body);if(!$('reader').open)$('reader').showModal();$('reader').scrollTop=0;
}
function render() {
 const id=location.hash.slice(1)||'overview';const section=SECTIONS.find(s=>s[0]===id)||SECTIONS[0];
 $('nav').innerHTML=SECTIONS.map(s=>`<a href="#${s[0]}" ${section[0]===s[0]?'class="active" aria-current="page"':''}><span>${s[1]}</span>${s[2]}</a>`).join('');$('breadcrumb').textContent=section[2];
 $('content').innerHTML=({overview,concept,plan,literature:()=>library(true),methods,analysis,weekly,notes:()=>library(false)})[section[0]]();
 if(['literature','notes'].includes(section[0])){
  const filter=()=>{const query=$('note-search').value.toLowerCase(),f=$('note-filter').value;const notes=corpus.notes.filter(n=>(section[0]!=='literature'||n.group==='Literatur')&&(!f||(section[0]==='literature'?n.body.includes(f):n.group===f))&&(!query||(n.title+' '+n.body).toLowerCase().includes(query)));$('note-results').innerHTML=noteCards(notes);$('result-count').textContent=notes.length+' catatan';};
  $('note-search').addEventListener('input',filter);$('note-filter').addEventListener('change',filter);
 }
 if(section[0]==='weekly')bindWeekly();
}
function checkpointMarkdown() {return '# Checkpoint PhD Monash\n\n'+[...state.entries].sort((a,b)=>a.week.localeCompare(b.week)).map(e=>`## Minggu ${e.week} · ${e.rq}\n\nStatus: ${STATUS[e.status]} · capaian target minggu: ${e.progress}%\n\n`+[['target','Target'],['achieved','Hasil'],['evidence','Bukti'],['blockers','Hambatan'],['next','Berikutnya'],['supervisor','Supervisi']].map(([k,l])=>`### ${l}\n\n${e[k]||'—'}\n`).join('\n')).join('\n');}
function bindWeekly() {
 $('weekly-form').addEventListener('submit',event=>{event.preventDefault();const f=new FormData(event.target);let week=f.get('week');const d=new Date(week+'T12:00:00');d.setDate(d.getDate()-((d.getDay()+6)%7));week=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
  const duplicate=state.entries.find(e=>e.week===week&&e.id!==editing);if(duplicate){toast('Minggu ini sudah memiliki checkpoint. Gunakan tombol Edit pada riwayat.');return;}
  const entry={id:editing||crypto.randomUUID(),week,rq:f.get('rq'),status:f.get('status'),progress:Number(f.get('progress')),updatedAt:new Date().toISOString()};for(const k of ['target','achieved','evidence','blockers','next','supervisor'])entry[k]=String(f.get(k)||'').trim();
  if(!entry.target||!validEntry(entry)){toast('Periksa isian target, tanggal dan capaian 0–100%.');return;}
  if(!saveState({...state,entries:[...state.entries.filter(e=>e.id!==entry.id),entry]}))return;
  editing=null;render();toast('Checkpoint tersimpan di browser ini.');
 });
 $('cancel-edit')?.addEventListener('click',()=>{editing=null;render();});
 $('export-json').onclick=()=>download('phd-monash-checkpoints.json',JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));
 $('export-md').onclick=()=>download('phd-monash-checkpoints.md',checkpointMarkdown(),'text/markdown');
 $('import-json').onclick=()=>$('import-file').click();
 $('import-file').onchange=async event=>{try{const file=event.target.files[0];if(!file)return;if(file.size>5000000)throw new Error('Berkas terlalu besar (maksimal 5 MB).');const incoming=validateState(JSON.parse(await file.text()));
   if(state.entries.length&&!confirm('Gabungkan cadangan? Checkpoint dengan minggu yang sama akan diganti oleh isi cadangan. Ekspor data saat ini dahulu jika diperlukan.'))return;
   const merged=new Map(state.entries.map(e=>[e.week,e]));incoming.entries.forEach(e=>merged.set(e.week,{...e,id:crypto.randomUUID()}));const next={version:1,entries:[...merged.values()],completed:[...new Set([...state.completed,...incoming.completed])]};if(saveState(next)){editing=null;render();toast('Cadangan berhasil diimpor.');}
  }catch(error){toast(error.message||'Berkas tidak dapat diimpor.');}};
}
document.addEventListener('click',event=>{
 const note=event.target.closest('[data-note]');if(note){openNote(noteByTitle(note.dataset.note));return;}
 const id=event.target.closest('[data-note-id]');if(id){openNote(corpus.notes.find(n=>n.id===id.dataset.noteId));return;}
 const edit=event.target.closest('[data-edit]');if(edit){editing=edit.dataset.edit;render();$('weekly-form').scrollIntoView({behavior:'smooth',block:'start'});return;}
 const del=event.target.closest('[data-delete]');if(del&&confirm('Hapus checkpoint ini dari browser? Ekspor cadangan jika ingin menyimpannya.')){if(saveState({...state,entries:state.entries.filter(e=>e.id!==del.dataset.delete)})){editing=null;render();toast('Checkpoint dihapus.');}}
 if(event.target.closest('#reader-back')){const previous=readerHistory.pop();if(previous)openNote(previous,true);}
});
document.addEventListener('change',event=>{const work=event.target.closest('[data-work]');if(!work)return;const completed=new Set(state.completed);work.checked?completed.add(work.dataset.work):completed.delete(work.dataset.work);if(saveState({...state,completed:[...completed]})){render();toast('Status paket kerja tersimpan.');}else work.checked=!work.checked;});
$('close-reader').onclick=()=>$('reader').close();$('reader').addEventListener('close',()=>{currentNote=null;readerHistory=[];});
$('download-note').onclick=()=>{if(currentNote)download(currentNote.title+'.md',currentNote.body,'text/markdown');};
window.addEventListener('hashchange',()=>{render();window.scrollTo({top:0,behavior:'smooth'});});
async function init() {loadState();try{const response=await fetch('notes.json');if(!response.ok)throw new Error('HTTP '+response.status);corpus=await response.json();if(!Array.isArray(corpus.notes))throw new Error('Format catatan tidak valid');render();}catch(error){$('content').innerHTML='<div class="empty error">Catatan belum dapat dimuat. Periksa koneksi lalu <button class="secondary" id="retry">coba lagi</button>.</div>';$('retry').onclick=init;}}
init();
