/* ============ EKUITAS vs KESETARAAN — lanjutan: spasial · waktu · skenario (D.kd.dyn) ============ */
(function(){
const $=id=>document.getElementById(id);
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=n=>(n==null||isNaN(n))?'—':Math.round(+n).toLocaleString('id-ID');
const f1=n=>(n==null||isNaN(n))?'—':(+n).toLocaleString('id-ID',{maximumFractionDigits:1,minimumFractionDigits:1});
const f2=n=>(n==null||isNaN(n))?'—':(+n).toLocaleString('id-ID',{maximumFractionDigits:2,minimumFractionDigits:2});
const f3=n=>(n==null||isNaN(n))?'—':(+n).toLocaleString('id-ID',{maximumFractionDigits:3,minimumFractionDigits:3});
const jt=n=>n>=1e6?(n/1e6).toLocaleString('id-ID',{maximumFractionDigits:1})+' jt':n>=1e3?(n/1e3).toLocaleString('id-ID',{maximumFractionDigits:0})+' rb':fmt(n);
const rp=n=>n>=1e12?'Rp '+(n/1e12).toLocaleString('id-ID',{maximumFractionDigits:2})+' T':n>=1e9?'Rp '+(n/1e9).toLocaleString('id-ID',{maximumFractionDigits:1})+' M':'Rp '+(n/1e6).toLocaleString('id-ID',{maximumFractionDigits:0})+' jt';
const NAVY='#16305f',GOLD='#d4af37',BLUE='#3a6ea5',GREEN='#2e9e5b',RED='#d6443c',ORANGE='#e8742c',MUT='#9aa6bd',PURPLE='#8a6fb0',TEAL='#1f8a99';
const CLSC={HH:RED,LL:BLUE,HL:ORANGE,LH:TEAL,ns:'#cfd6e2'};
const CLSL={HH:'tinggi–tinggi (HH)',LL:'rendah–rendah (LL)',HL:'tinggi di tengah rendah (HL)',LH:'rendah di tengah tinggi (LH)',ns:'tidak signifikan'};
const C={};
function mk(id,cfg){if(C[id])C[id].destroy();const el=$(id);if(!el||typeof Chart==='undefined')return;C[id]=new Chart(el,cfg);}
const leg=()=>({position:'bottom',labels:{boxWidth:10,font:{size:10}}});
const yAx=(t,o)=>Object.assign({beginAtZero:true,grid:{color:'#eef1f6'},title:{display:!!t,text:t,font:{size:10}},ticks:{font:{size:10}}},o||{});
const xAx=t=>({grid:{display:false},title:{display:!!t,text:t,font:{size:10}},ticks:{font:{size:10}}});
const kv=(arr)=>arr.map(x=>`<div class="${x[2]||''}"><div class="v">${x[0]}</div><div class="t">${x[1]}</div></div>`).join('');
let lisaMap=null;

window.buildKdDyn=function(Y,K){
 const S=Y.spatial,T=Y.time,SC=Y.scen,M=Y.meta;
 /* ================= 6 spasial ================= */
 const sc=Object.fromEntries(S.summary.chargers.map(s=>[s.cls,s])),sa=Object.fromEntries(S.summary.access.map(s=>[s.cls,s]));
 $('kdKv6').innerHTML=kv([[f3(S.moran.chargers.I),'Moran\'s I charger/kapita (log) · z '+f1(S.moran.chargers.z)+', p '+f3(S.moran.chargers.p),'g'],[f3(S.moran.access.I),'Moran\'s I akses ≤10 km · z '+f1(S.moran.access.z)],[f3(S.moran.hex_dist.I),'Moran\'s I jarak ke SPKLU per heksagon'],[sc.HH.n+' kab · '+sc.HH.pop_pct+'%','klaster tinggi–tinggi: kabupaten · penduduk'],[sc.LL.n+' kab · '+sc.LL.pop_pct+'%','klaster rendah–rendah: kabupaten · penduduk'],[S.zero_nb_zero+' / '+S.zero_total,'kab tanpa charger yang semua tetangganya juga tanpa charger']]);
 const byCls={};S.kab.forEach(k=>{(byCls[k.cls]=byCls[k.cls]||[]).push(k);});
 mk('cKdMoran',{type:'scatter',data:{datasets:['ns','HL','LH','LL','HH'].filter(c=>byCls[c]).map(c=>({label:CLSL[c],data:byCls[c].map(k=>({x:k.z,y:k.lag,k})),backgroundColor:c==='ns'?'rgba(160,170,190,.45)':CLSC[c],pointRadius:c==='ns'?2.5:4.5,pointHoverRadius:6}))},
  options:{maintainAspectRatio:false,plugins:{legend:leg(),tooltip:{callbacks:{label:x=>`${x.raw.k.name} (${x.raw.k.prov}): ${f2(x.raw.k.per100k)}/100 rb · z ${f2(x.raw.k.z)} · tetangga ${f2(x.raw.k.lag)} · p ${x.raw.k.p}`}}},
   scales:{x:{grid:{color:'#eef1f6'},title:{display:true,text:'z charger/kapita kabupaten (log, dipusatkan)',font:{size:10}},ticks:{font:{size:10}}},y:{grid:{color:'#eef1f6'},title:{display:true,text:'rata-rata z tetangga (lag spasial)',font:{size:10}},ticks:{font:{size:10}}}}}});
 const cls5=['HH','LL','HL','LH','ns'];
 mk('cKdLisa',{data:{labels:cls5.map(c=>CLSL[c]),datasets:[{type:'bar',label:'% penduduk',data:cls5.map(c=>sc[c].pop_pct),backgroundColor:cls5.map(c=>CLSC[c]),yAxisID:'y',borderRadius:3},{type:'line',label:'charger /100 rb',data:cls5.map(c=>sc[c].per100k),borderColor:NAVY,backgroundColor:NAVY,pointRadius:4,yAxisID:'y2'},{type:'line',label:'≤10 km %',data:cls5.map(c=>sc[c].within10),borderColor:GREEN,backgroundColor:GREEN,pointRadius:4,borderDash:[4,3],yAxisID:'y'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg()},scales:{y:yAx('% penduduk · % ≤10 km',{max:100}),y2:{position:'right',beginAtZero:true,grid:{display:false},title:{display:true,text:'charger /100 rb',font:{size:10}},ticks:{font:{size:10}}},x:{grid:{display:false},ticks:{font:{size:9}}}}}});
 mk('cKdLLProv',{type:'bar',data:{labels:S.ll_prov.map(p=>p.name),datasets:[{data:S.ll_prov.map(p=>Math.round(p.pop/1e4)/100),backgroundColor:BLUE,borderRadius:3}]},
  options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:x=>x.raw+' juta jiwa di klaster LL'}}},scales:{x:yAx('juta jiwa'),y:{grid:{display:false},ticks:{font:{size:10}}}}}});
 $('tblKdHH').querySelector('tbody').innerHTML=S.hh.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.prov)}</td><td class="n">${f2(r.per100k)}</td><td class="n">${f2(r.lag)}</td></tr>`).join('');
 $('tblKdLL').querySelector('tbody').innerHTML=S.ll.map(r=>`<tr><td><b>${esc(r.name)}</b></td><td>${esc(r.prov)}</td><td class="n">${fmt(r.pop)}</td><td class="n" style="color:${r.chargers?'inherit':RED};font-weight:700">${r.chargers}</td><td class="n">${f1(r.within10)}</td></tr>`).join('');
 // peta LISA (Leaflet, lingkaran per kabupaten)
 try{
  if(typeof L!=='undefined'&&$('kdLisaMap')){
   if(lisaMap){lisaMap.remove();lisaMap=null;}
   lisaMap=L.map('kdLisaMap',{preferCanvas:true,scrollWheelZoom:false}).setView([-2.5,118],4);
   L.tileLayer('https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png',{attribution:'© OSM © CARTO · geoBoundaries · Kontur · PLN',maxZoom:19}).addTo(lisaMap);
   const order={ns:0,LH:1,HL:2,LL:3,HH:4};
   S.kab.slice().sort((a,b)=>order[a.cls]-order[b.cls]).forEach(k=>{
    const r=Math.max(3,Math.min(22,Math.sqrt(k.pop/6e4)));
    L.circleMarker([k.lat,k.lng],{radius:r,color:k.cls==='ns'?'#9aa6bd':CLSC[k.cls],weight:k.cls==='ns'?.6:1.2,fillColor:CLSC[k.cls],fillOpacity:k.cls==='ns'?.25:.75})
     .bindPopup(`<div class="lisa-pop"><b>${esc(k.name)}</b> · ${esc(k.prov)}<br>${CLSL[k.cls]} (p ${k.p})<br>penduduk ${fmt(k.pop)} · charger/100 rb <b>${f2(k.per100k)}</b> · ≤10 km ${f1(k.within10)} %<br>z ${f2(k.z)} · tetangga ${f2(k.lag)} · ${k.deg} tetangga · akses: ${CLSL[k.cls_acc]}</div>`).addTo(lisaMap);
   });
   const lg=L.control({position:'bottomleft'});lg.onAdd=()=>{const d=L.DomUtil.create('div');d.style.cssText='background:rgba(255,255,255,.92);padding:6px 9px;border-radius:8px;font-size:10px;line-height:1.6;border:1px solid #d9e0ec';d.innerHTML=cls5.map(c=>`<span style="display:inline-block;width:9px;height:9px;border-radius:50%;background:${CLSC[c]};margin-right:5px"></span>${CLSL[c]}`).join('<br>');return d;};lg.addTo(lisaMap);
   setTimeout(()=>lisaMap&&lisaMap.invalidateSize(),150);
  }
 }catch(e){console.warn('peta LISA',e);}
 const llTop=S.ll_prov[0],hhProv={};S.kab.filter(k=>k.cls==='HH').forEach(k=>hhProv[k.prov]=(hhProv[k.prov]||0)+1);
 const hhP=Object.entries(hhProv).sort((a,b)=>b[1]-a[1]).slice(0,4);
 $('kdWhy6').innerHTML=`<b>Mengapa Moran's I ${S.moran.chargers.I} dan apa artinya.</b><ol>
  <li><b>Ketimpangan ini mengelompok, bukan acak.</b> Moran's I ${S.moran.chargers.I} (harapan acak ${S.moran.chargers.EI}, z = ${S.moran.chargers.z}, p = ${S.moran.chargers.p}) berarti kabupaten dengan charger/kapita tinggi bertetangga dengan yang tinggi, dan yang rendah dengan yang rendah. Untuk akses ≤10 km lebih kuat lagi (I = ${S.moran.access.I}): cakupan adalah fenomena wilayah karena satu situs melayani lintas batas kabupaten. Di tingkat heksagon, jarak ke SPKLU nyaris kontinu di ruang (I = ${S.moran.hex_dist.I}) — gurun pengisian adalah hamparan, bukan lubang.</li>
  <li><b>Dua jenis klaster yang berbeda sifat.</b> Klaster <b>tinggi–tinggi</b>: ${sc.HH.n} kabupaten/kota, ${sc.HH.pop_pct}% penduduk, ${f2(sc.HH.per100k)} charger/100 rb, ${f1(sc.HH.within10)}% ≤10 km — ${hhP.map(p=>`${esc(p[0])} (${p[1]})`).join(', ')}: Jabodetabek dan Bali, wilayah tempat pasar dan PLN saling menguatkan. Klaster <b>rendah–rendah</b>: ${sc.LL.n} kabupaten, ${sc.LL.pop_pct}% penduduk (${jt(S.ll_prov.reduce((a,p)=>a+p.pop,0))} jiwa), ${f2(sc.LL.per100k)} charger/100 rb, hanya ${f1(sc.LL.within10)}% ≤10 km; ${jt(llTop.pop)} jiwa di antaranya di ${esc(llTop.name)}. Klaster LL berpenduduk kecil tetapi luas — inilah wilayah yang tidak akan pernah dipilih aturan cakupan per situs.</li>
  <li><b>Kabupaten tanpa charger bukan pulau kecil di lautan charger.</b> Dari ${S.zero_total} kabupaten tanpa charger, ${S.zero_nb_zero} dikelilingi seluruhnya oleh kabupaten tanpa charger (semua di Papua pegunungan); ${S.zero_total-S.zero_nb_zero} lainnya berbatasan dengan kabupaten ber-charger — untuk mereka, "meminjam" situs tetangga sudah memberi sebagian akses (itulah sebabnya Gini akses jauh lebih rendah daripada Gini kepemilikan). Kebijakan untuk keduanya berbeda: pertama butuh jaringan listrik dan logistik regional, kedua cukup satu situs per kabupaten.</li>
  <li><b>Outlier yang informatif.</b> ${sc.HL.n} kabupaten tinggi di tengah tetangga rendah (HL: kota-kota luar Jawa yang jadi simpul — ${S.kab.filter(k=>k.cls==='HL').slice(0,4).map(k=>esc(k.name)).join(', ')}) dan ${sc.LH.n} rendah di tengah tinggi (LH: ${S.kab.filter(k=>k.cls==='LH').map(k=>esc(k.name)).join(', ')}) — kabupaten yang "tertinggal di lingkungan maju" adalah target termurah karena jaringan dan permintaan tetangganya sudah ada.</li>
  <li><b>Konsekuensi metodologis:</b> karena residu Gini berkorelasi spasial, uji statistik antar-kabupaten (mis. regresi charger ~ IPM) harus memakai model spasial (SAR/SEM atau galat berkelompok per provinsi); Theil ${K.theil.prov.between_pct}% antar-provinsi (§1) dan Moran's I di sini saling menguatkan bahwa unit kebijakan yang tepat adalah <i>wilayah</i>, bukan kabupaten satu per satu.</li></ol>`;

 /* ================= 7 waktu ================= */
 const JB=T.jabar.series,NT=T.nat.series,CB=T.nat.calib;
 const jb0=JB[1],jbL=JB[JB.length-1],nt24=NT.find(s=>s.label==='2024'),ntPLN=NT[NT.length-2],ntAll=NT[NT.length-1],nt21=NT[0];
 $('kdKv7').innerHTML=kv([[f3(jb0.gini)+' → '+f3(jbL.gini),'Jawa Barat: Gini '+jb0.label+' → '+jbL.label+' ('+jb0.units+' → '+jbL.units+' unit)','g'],[f1(jb0.within10)+'% → '+f1(jbL.within10)+'%','Jawa Barat: penduduk ≤10 km'],[f3(nt21.gini)+' → '+f3(nt24.gini)+' → '+f3(ntPLN.gini),'nasional PLN: Gini 2021 → 2024 → Jun 2026'],[f3(ntPLN.gini)+' → '+f3(ntAll.gini),'Gini PLN saja → PLN + mitra (2026)'],[f1(ntPLN.within10)+'% → '+f1(ntAll.within10)+'%','cakupan ≤10 km: PLN saja → + '+fmt(T.nat.n_mitra)+' situs mitra'],[f1(CB.acc)+'%','akurasi tahun estimasi (n='+CB.n+', ρ='+f2(CB.rho)+')']]);
 mk('cKdJbTime',{data:{labels:JB.map(s=>s.label),datasets:[{type:'line',label:'Gini charger/kapita (26 kab/kota)',data:JB.map(s=>s.gini),borderColor:NAVY,backgroundColor:NAVY,pointRadius:4,yAxisID:'y'},{type:'line',label:'≤10 km %',data:JB.map(s=>s.within10),borderColor:GREEN,backgroundColor:GREEN,pointRadius:3,yAxisID:'y2'},{type:'line',label:'≤5 km %',data:JB.map(s=>s.within5),borderColor:TEAL,backgroundColor:TEAL,pointRadius:3,borderDash:[4,3],yAxisID:'y2'},{type:'bar',label:'unit charger kumulatif',data:JB.map(s=>s.units),backgroundColor:'rgba(212,175,55,.35)',yAxisID:'y3'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg()},scales:{y:yAx('Gini',{max:1}),y2:{position:'right',beginAtZero:true,max:100,grid:{display:false},title:{display:true,text:'% penduduk',font:{size:10}},ticks:{font:{size:10}}},y3:{display:false,beginAtZero:true},x:xAx('')}}});
 mk('cKdJbNew',{type:'bar',data:{labels:JB.map(s=>s.label),datasets:[{label:'unit baru di kota',data:JB.map(s=>s.new_kota),backgroundColor:NAVY,stack:'s'},{label:'unit baru di kabupaten',data:JB.map(s=>s.new_units-s.new_kota),backgroundColor:'#c9d4e8',stack:'s'},{type:'line',label:'porsi 3 kab/kota teratas %',data:JB.map(s=>s.top3_share),borderColor:RED,backgroundColor:RED,pointRadius:3,yAxisID:'y2'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg()},scales:{y:yAx('unit charger baru',{stacked:true}),y2:{position:'right',beginAtZero:true,max:100,grid:{display:false},title:{display:true,text:'% unit di 3 teratas',font:{size:10}},ticks:{font:{size:10}}},x:{stacked:true,grid:{display:false},ticks:{font:{size:10}}}}}});
 mk('cKdNatTime',{data:{labels:NT.map(s=>s.label),datasets:[{type:'line',label:'Gini antar-kabupaten',data:NT.map(s=>s.gini),borderColor:NAVY,backgroundColor:NAVY,pointRadius:4,yAxisID:'y'},{type:'line',label:'Gini antar-provinsi',data:NT.map(s=>s.gini_prov),borderColor:BLUE,backgroundColor:BLUE,pointRadius:3,borderDash:[4,3],yAxisID:'y'},{type:'line',label:'Theil: porsi antar-provinsi %',data:NT.map(s=>s.theil_prov_pct),borderColor:PURPLE,backgroundColor:PURPLE,pointRadius:3,yAxisID:'y2'},{type:'bar',label:'kabupaten tanpa charger',data:NT.map(s=>s.zero),backgroundColor:'rgba(214,68,60,.25)',yAxisID:'y3'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg()},scales:{y:yAx('Gini',{max:1}),y2:{position:'right',beginAtZero:true,max:100,grid:{display:false},title:{display:true,text:'% Theil antar-provinsi',font:{size:10}},ticks:{font:{size:10}}},y3:{display:false,beginAtZero:true},x:xAx('')}}});
 mk('cKdNatCov',{data:{labels:NT.map(s=>s.label),datasets:[{type:'line',label:'≤10 km %',data:NT.map(s=>s.within10),borderColor:GREEN,backgroundColor:GREEN,pointRadius:3,yAxisID:'y'},{type:'line',label:'≤25 km %',data:NT.map(s=>s.within25),borderColor:TEAL,backgroundColor:TEAL,pointRadius:3,borderDash:[4,3],yAxisID:'y'},{type:'line',label:'kuintil termiskin ≤10 km %',data:NT.map(s=>s.q1_within10),borderColor:GOLD,backgroundColor:GOLD,pointRadius:3,yAxisID:'y'},{type:'bar',label:'situs operasional',data:NT.map(s=>s.sites),backgroundColor:'rgba(22,48,95,.18)',yAxisID:'y2'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg()},scales:{y:yAx('% penduduk',{max:100}),y2:{position:'right',beginAtZero:true,grid:{display:false},title:{display:true,text:'situs',font:{size:10}},ticks:{font:{size:10}}},x:xAx('')}}});
 $('tblKdNat').querySelector('tbody').innerHTML=NT.map(s=>`<tr${s.label.includes('mitra')?' style="background:#fff7e3"':''}><td><b>${esc(s.label)}</b></td><td class="n">${fmt(s.sites)}</td><td class="n">${fmt(s.chargers)}</td><td class="n">${f3(s.gini)}</td><td class="n">${f3(s.gini_prov)}</td><td class="n">${f1(s.theil_prov_pct)}</td><td class="n">${s.zero}</td><td class="n">${f1(s.kota_ratio)}×</td><td class="n">${f1(s.java_share)}</td><td class="n">${f1(s.within10)}</td><td class="n">${f1(s.within25)}</td><td class="n">${f1(s.q1_within10)}</td></tr>`).join('');
 $('kdCalib').innerHTML=`<b>Kalibrasi tahun nasional.</b> Master SPKLU nasional tidak memuat tanggal operasi. ID SPKLU PLN diberikan berurutan saat situs didaftarkan, dan pada ${CB.n} situs Jawa Barat yang tanggalnya tercatat, urutan ID dan tanggal operasi berkorelasi ρ Spearman = <b>${CB.rho}</b>. Batas ID per tahun dipilih yang memaksimalkan kecocokan: ${CB.per_year.map((p,i)=>`${p.y}: ${i?'ID ≥ '+CB.cuts[i-1]:'ID < '+CB.cuts[0]}${i<CB.cuts.length?' – '+(CB.cuts[i]-1):'+'} (median ${p.id_med}, n=${p.n})`).join(' · ')}. Akurasi tahun pada sampel kalibrasi <b>${CB.acc}%</b> (±1 tahun ${CB.acc1}%). Berlaku hanya untuk ${fmt(T.nat.n_pln)} situs PLN aktif (${T.nat.n_uncal} situs PLN ber-ID ≥10000 dimasukkan ke 2026); ${fmt(T.nat.n_mitra)} situs mitra tidak punya ID berurutan sehingga hanya muncul di titik akhir. Deret ini juga <i>survivor</i>: situs PLN yang kini <i>unavailable/maintenance</i> tidak ikut. Jawa Barat memakai tanggal nyata ${fmt(T.jabar.units)} unit (${fmt(T.jabar.pln_units)} PLN); Kota Cimahi tidak punya heksagon sendiri dan digabung ke ${esc(T.jabar.cimahi_to)}.`;
 const jbPeak=JB.reduce((a,s)=>s.gini>a.gini&&s.units>50?s:a,JB[1]);
 $('kdWhy7').innerHTML=`<b>Mengapa Gini turun lalu naik lagi.</b><ol>
  <li><b>Fase 1 (2021–2024): jaringan PLN menyebar, ketimpangan runtuh.</b> Gini antar-kabupaten nasional ${nt21.gini} (${nt21.sites} situs, ${nt21.zero} kabupaten kosong) → ${nt24.gini} pada 2024 (${fmt(nt24.sites)} situs, ${nt24.zero} kosong); cakupan ≤10 km ${nt21.within10}% → ${nt24.within10}%, kuintil termiskin ${nt21.q1_within10}% → ${nt24.q1_within10}%. Lonjakan 2024 (${fmt(nt24.sites-NT[2].sites)} situs PLN dalam setahun, ${nt24.provs} provinsi terisi) adalah program "satu SPKLU per kabupaten/ULP" — pemerataan <i>keberadaan</i>, dan Gini menangkapnya.</li>
  <li><b>Fase 2 (2025–2026): pertumbuhan berbalik ke pusat.</b> Setelah 2024 Gini PLN naik ke ${ntPLN.gini}, rasio kota/kabupaten dari ${nt24.kota_ratio}× menjadi ${ntPLN.kota_ratio}×, porsi Jawa ${nt24.java_share}% → ${ntPLN.java_share}%, porsi Theil antar-provinsi ${nt24.theil_prov_pct}% → ${ntPLN.theil_prov_pct}%; kuintil termiskin nyaris tidak bergerak (${nt24.q1_within10}% → ${ntPLN.q1_within10}%). Situs-situs baru menebalkan kota yang sudah terlayani (permintaan armada) — cakupan hanya naik ${(ntPLN.within10-nt24.within10).toFixed(1)} poin dari ${fmt(ntPLN.sites-nt24.sites)} situs.</li>
  <li><b>Mitra non-PLN adalah mesin ketimpangan terbesar.</b> Menambahkan ${fmt(T.nat.n_mitra)} situs mitra (+${fmt(ntAll.chargers-ntPLN.chargers)} charger) hanya menaikkan cakupan ${(ntAll.within10-ntPLN.within10).toFixed(2)} poin tetapi menaikkan Gini dari ${ntPLN.gini} ke <b>${ntAll.gini}</b>, rasio kota/kabupaten ke ${ntAll.kota_ratio}×, dan porsi Jawa ke ${ntAll.java_share}%. Pasar menaruh charger di tempat yang sudah punya charger. Implikasi untuk RQ4: Gini 0,595 di §1 adalah <i>Gini pasar + PLN</i>; Gini PLN sendiri ${ntPLN.gini}. Instrumen pemerataan yang ada (PLN) bekerja, tetapi dibanjiri instrumen pasar yang tidak.</li>
  <li><b>Jawa Barat mengulang pola yang sama dengan data tanggal nyata.</b> Gini ${jb0.gini} (${jb0.label}) → ${jbPeak.gini} (${jbPeak.label}, saat unit baru menumpuk di kota: ${jbPeak.new_kota} dari ${jbPeak.new_units}) → ${jbL.gini} (${jbL.label}); cakupan ≤10 km ${jb0.within10}% → ${jbL.within10}% tetapi ≤5 km hanya ${jb0.within5}% → ${jbL.within5}%: ekspansi 2025–2026 menebalkan (unit per situs naik dari ${(JB[2].units/JB[2].sites).toFixed(1)} ke ${(jbL.units/jbL.sites).toFixed(1)}) lebih daripada meluaskan. Rasio kota/kabupaten per kapita Jawa Barat ${jbL.kota_ratio}× — jauh lebih rendah daripada nasional ${ntAll.kota_ratio}× — karena satu provinsi padat dengan satu operator dominan (PLN UID Jabar) berperilaku seperti "fase 1" terus-menerus.</li>
  <li><b>Kesimpulan dinamis:</b> ketimpangan SPKLU bukan warisan statis yang tinggal dikejar; ia <i>diproduksi ulang</i> setiap tahun oleh komposisi pembangunan baru. Ukuran keberhasilan pemerataan karena itu harus <i>marjinal</i> — ke mana situs tahun ini pergi — bukan stok kumulatif.</li></ol>`;

 /* ================= 8 skenario ================= */
 const WF=SC.wf_targets,MX=SC.mix,BASE=SC.base;
 let cost=400;const costEl=$('kdCost');
 const render8=()=>{
  const rpN=n=>rp(n*cost*1e6);
  $('kdCostV').textContent='Rp '+cost.toLocaleString('id-ID')+' jt / charger';
  $('kdKv8').innerHTML=kv(WF.map((w,i)=>[fmt(w.N)+' · '+rpN(w.N),'charger tambahan untuk Gini '+f1(w.target)+' (+'+f1(w.pct)+'% jaringan, '+w.kab+' kabupaten)',i===1?'g':'']).concat([[f3(BASE.gini),'Gini kini (508 kab/kota)'],[f2(SC.mean100k),'rata-rata charger /100 rb kini']]));
  $('tblKdWf').querySelector('tbody').innerHTML=WF.map(w=>`<tr><td><b>${f1(w.target)}</b></td><td class="n">${f2(w.t)}</td><td class="n"><b>${fmt(w.N)}</b></td><td class="n">${f1(w.pct)}</td><td class="n">${w.kab}</td><td class="n">${rpN(w.N)}</td><td class="n">${f1(w.kota_share)}</td><td class="n">${f1(w.java_share)}</td><td class="n">${f1(w.zero_share)}</td></tr>`).join('');
  $('tblKdMix').querySelector('tbody').innerHTML=M.budgets.map(b=>{const rows=MX.map(m=>({f:m.f,a:m.at.find(x=>x.n===b)}));const r0=rows[0].a;return rows.map((r,i)=>{const dg=r0.gini-r.a.gini,dc=r0.cov-r.a.cov;return `<tr${i===0?' style="border-top:2px solid #c9d4e8"':''}><td>${i===0?'<b>'+fmt(b)+' situs</b>':''}</td><td class="n">${Math.round(r.f*100)} %</td><td class="n">${rpN(b*M.ch_site)}</td><td class="n">${f1(r.a.cov)}</td><td class="n"><b>${f3(r.a.gini)}</b></td><td class="n">${f1(r.a.q1)}</td><td class="n">${f1(r.a.luar_java)}</td><td class="n">${f1(r.a.kota)}</td><td class="n">${i===0?'—':dg>0.0005?f2(dc/(dg*100)):'∞'}</td></tr>`;}).join('');}).join('');
 };
 if(costEl){costEl.oninput=()=>{cost=+costEl.value;render8();};}
 render8();
 mk('cKdWater',{type:'line',data:{datasets:[{label:'Gini setelah penambahan (water-filling)',data:SC.wf_curve.filter(p=>p[1]<=6000).map(p=>({x:p[1],y:p[2],t:p[0]})),borderColor:NAVY,pointRadius:0,borderWidth:2.2,tension:.2},{label:'target',data:WF.map(w=>({x:w.N,y:w.target,t:w.t})),type:'scatter',backgroundColor:GOLD,pointRadius:6,pointStyle:'rectRot'}]},
  options:{maintainAspectRatio:false,plugins:{legend:leg(),tooltip:{callbacks:{label:x=>`+${fmt(x.raw.x)} charger → Gini ${f3(x.raw.y)} (ambang ${f2(x.raw.t)}/100 rb)`}}},scales:{x:{type:'linear',min:0,max:6000,grid:{color:'#eef1f6'},title:{display:true,text:'charger tambahan (jaringan kini '+fmt(SC.total)+')',font:{size:10}},ticks:{font:{size:10}}},y:yAx('Gini charger/kapita',{max:.7})}}});
 const sel=$('kdWfSel');sel.innerHTML=WF.map((w,i)=>`<option value="${i}"${i===1?' selected':''}>Gini ${w.target}</option>`).join('');
 const renderWf=()=>{const w=WF[+sel.value];
  $('tblKdWfFirst').querySelector('tbody').innerHTML=w.first.map((r,i)=>`<tr><td class="n">${i+1}</td><td><b>${esc(r.name)}</b></td><td>${esc(r.prov)}</td><td class="n">${fmt(r.pop)}</td><td class="n">${r.chargers}</td><td class="n" style="color:${RED};font-weight:700">+${r.need}</td></tr>`).join('');
  mk('cKdWfProv',{type:'bar',data:{labels:w.prov.map(p=>p.name),datasets:[{data:w.prov.map(p=>p.N),backgroundColor:w.prov.map(p=>['Banten','DKI Jakarta','Jawa Barat','Jawa Tengah','DI Yogyakarta','Jawa Timur'].includes(p.name)?NAVY:BLUE),borderRadius:3}]},
   options:{indexAxis:'y',maintainAspectRatio:false,plugins:{legend:{display:false},tooltip:{callbacks:{label:x=>fmt(x.raw)+' charger ('+w.prov[x.dataIndex].pct+'% dari '+fmt(w.N)+')'}}},scales:{x:yAx('charger tambahan'),y:{grid:{display:false},ticks:{font:{size:10}}}}}});};
 sel.onchange=renderWf;renderWf();
 const BC=[NAVY,BLUE,GREEN,GOLD];
 mk('cKdFrontier',{type:'line',data:{datasets:M.budgets.map((b,i)=>({label:fmt(b)+' situs',data:MX.map(m=>{const a=m.at.find(x=>x.n===b);return {x:a.gini,y:a.cov,f:m.f};}),borderColor:BC[i],backgroundColor:BC[i],pointRadius:MX.map(m=>3+m.f*5),showLine:true,tension:.2,borderWidth:1.8})).concat([{label:'kini',data:[{x:BASE.gini,y:BASE.cov,f:null}],backgroundColor:RED,borderColor:RED,pointRadius:7,pointStyle:'star',showLine:false}])},
  options:{maintainAspectRatio:false,plugins:{legend:leg(),tooltip:{callbacks:{label:x=>x.raw.f==null?`kini: Gini ${f3(x.raw.x)}, cakupan ${f1(x.raw.y)}%`:`${x.dataset.label}, f = ${Math.round(x.raw.f*100)}%: Gini ${f3(x.raw.x)}, cakupan ${f1(x.raw.y)}%`}}},scales:{x:{type:'linear',reverse:true,grid:{color:'#eef1f6'},title:{display:true,text:'Gini charger/kapita antar-kabupaten (← lebih setara)',font:{size:10}},ticks:{font:{size:10}}},y:yAx('% penduduk ≤10 km',{min:60,max:100,beginAtZero:false})}}});
 const MC=[NAVY,BLUE,PURPLE,ORANGE,GOLD];
 mk('cKdMixCurve',{type:'line',data:{datasets:MX.map((m,i)=>({label:'f = '+Math.round(m.f*100)+'%',data:m.curve.map(c=>({x:c.n,y:c.gini})),borderColor:MC[i],pointRadius:0,borderWidth:1.8,tension:.2}))},
  options:{maintainAspectRatio:false,plugins:{legend:leg(),tooltip:{callbacks:{label:x=>`${x.dataset.label}: +${x.raw.x} situs → Gini ${f3(x.raw.y)}`}}},scales:{x:{type:'linear',grid:{color:'#eef1f6'},title:{display:true,text:'situs baru (2 charger per situs)',font:{size:10}},ticks:{font:{size:10}}},y:yAx('Gini',{max:.7})}}});
 const a0=k=>MX[0].at.find(x=>x.n===k),a1=k=>MX[MX.length-1].at.find(x=>x.n===k),a5=k=>MX[2].at.find(x=>x.n===k);
 const w4=WF[1],w3=WF[2],w2=WF[3],zll=S.ll.find(x=>x.chargers===0);
 $('kdWhy8').innerHTML=`<b>Mengapa pemerataan "murah" di awal dan mahal di ujung.</b><ol>
  <li><b>Gini 0,5 hanya butuh ${fmt(WF[0].N)} charger (+${WF[0].pct}%)</b>, Gini 0,4 ${fmt(w4.N)} (+${w4.pct}%), Gini 0,3 ${fmt(w3.N)}, Gini 0,2 ${fmt(w2.N)} (+${w2.pct}%). Kurva cembung: tiap 0,1 poin Gini berikutnya menuntut kira-kira dua kali charger sebelumnya, karena ambang per kapita yang harus dicapai naik (${f2(WF[0].t)} → ${f2(w2.t)}/100 rb) dan kabupaten berpenduduk besar ikut terseret. Pada asumsi biaya yang dipilih, lihat rupiah di kartu di atas — geser slidernya.</li>
  <li><b>Siapa yang menerima lebih dulu bukan Papua, melainkan kabupaten padat Jawa.</b> Pada target Gini 0,4, ${w4.java_share}% charger tambahan jatuh ke Jawa (${w4.prov.slice(0,3).map(p=>esc(p.name)+' '+fmt(p.N)).join(', ')}), hanya ${w4.zero_share}% ke ${K.why.kab_zero} kabupaten tanpa charger, dan ${w4.kota_share}% ke kota. Ukuran per kapita adalah ukuran <i>orang</i>, dan orang ada di Jawa (Kota Batam ikut muncul hanya karena SPKLU PLN Batam tidak ada di master — gurun palsu): pemerataan per kapita dan pemerataan wilayah adalah dua kebijakan berbeda dengan penerima berbeda —${esc(w4.first[0].name)} (+${w4.first[0].need}) vs ${zll?`${esc(zll.name)} (0 charger, ${fmt(zll.pop)} jiwa) yang di water-filling hanya butuh ${Math.ceil(w4.t*zll.pop/1e5)} unit`:'kabupaten kosong di Papua yang hanya butuh beberapa unit'}.</li>
  <li><b>Batas trade-off: pemerataan membeli Gini dengan cakupan, dan harganya naik tajam.</b> Pada ${fmt(M.budgets[2])} situs, aturan cakupan murni (f = 0) mencapai ${f1(a0(1000).cov)}% penduduk ≤10 km dengan Gini ${f3(a0(1000).gini)}; aturan pemerataan murni (f = 100%) ${f1(a1(1000).cov)}% dengan Gini ${f3(a1(1000).gini)} — <b>−${(a0(1000).cov-a1(1000).cov).toFixed(1)} poin cakupan untuk −${(a0(1000).gini-a1(1000).gini).toFixed(3)} Gini</b>. Campuran 50/50 mengambil sebagian besar manfaat keduanya (${f1(a5(1000).cov)}%, Gini ${f3(a5(1000).gini)}). Pada ${fmt(M.budgets[3])} situs aturan cakupan murni bahkan menaikkan Gini lagi (${f3(a0(1000).gini)} → ${f3(a0(2000).gini)}) karena situs ke-1.000 dan seterusnya mengisi kabupaten luas berpenduduk jarang (${MX[0].top_kab.slice(0,3).map(k=>esc(k.name)).join(', ')}) sampai per kapitanya melampaui rata-rata.</li>
  <li><b>Paradoks kuintil termiskin.</b> Aturan cakupan (f = 0) menutup kuintil termiskin lebih cepat (${f1(a0(1000).q1)}% pada 1.000 situs) daripada aturan pemerataan (${f1(a1(1000).q1)}%): cakupan mengejar penduduk belum terlayani — yang kebetulan miskin dan di luar Jawa (${f1(a0(1000).luar_java)}% situs di luar Jawa) — sedangkan pemerataan per kapita menarik situs kembali ke Jawa (${f1(a1(1000).luar_java)}% di luar Jawa; penerima terbesar ${MX[MX.length-1].top_kab.slice(0,3).map(k=>esc(k.name)).join(', ')}). <b>Kesetaraan per kapita ≠ ekuitas bagi yang termiskin.</b> Untuk RQ4 ini berarti fungsi tujuan harus dipilih eksplisit: cakupan kuintil termiskin (ekuitas), Gini per kapita (kesetaraan), atau cakupan nasional (efisiensi) — ketiganya tidak bisa dimaksimalkan bersama setelah ±500 situs.</li>
  <li><b>Rekomendasi yang bisa dipertahankan dari kurva ini:</b> 500 situs pertama hampir bebas konflik (semua f memberi cakupan ${f1(a1(500).cov)}–${f1(a0(500).cov)}% dan Gini ${f3(a0(500).gini)}–${f3(a1(500).gini)}); di atas itu, alokasikan f ≈ 50% lewat formula per kapita kabupaten dan 50% lewat cakupan, dan laporkan ketiga ukuran sekaligus. Water-filling ke Gini 0,4 (${fmt(w4.N)} charger) adalah anggaran pemerataan yang masuk akal untuk satu RUPTL.</li></ol>`;

 /* ================= 9 kesimpulan lanjutan ================= */
 $('kdConcl2').innerHTML=`<b>Kesimpulan lanjutan (§6–§8).</b><ol style="margin-left:18px">
  <li><b>Ketimpangan mengelompok di ruang (Moran's I ${S.moran.chargers.I}, akses ${S.moran.access.I}):</b> ${sc.HH.n} kabupaten/kota HH di Jabodetabek–Bali memegang ${f2(sc.HH.per100k)} charger/100 rb; ${sc.LL.n} kabupaten LL (${jt(S.ll_prov.reduce((a,p)=>a+p.pop,0))} jiwa, ${jt(llTop.pop)} di Papua) ${f2(sc.LL.per100k)}. Unit kebijakan yang tepat adalah wilayah; model statistik antar-kabupaten harus spasial.</li>
  <li><b>Ketimpangan diproduksi ulang, bukan diwarisi:</b> PLN menurunkan Gini ${nt21.gini} → ${nt24.gini} (2021–2024) lalu pertumbuhan berbalik ke kota (${ntPLN.gini} pada 2026); mitra non-PLN menaikkannya ke ${ntAll.gini} sambil menambah cakupan hanya ${(ntAll.within10-ntPLN.within10).toFixed(2)} poin. Ukur pemerataan secara marjinal per tahun.</li>
  <li><b>Harga pemerataan terukur:</b> Gini 0,4 = +${fmt(w4.N)} charger, Gini 0,3 = +${fmt(w3.N)}, Gini 0,2 = +${fmt(w2.N)} (water-filling); pada 1.000 situs, pemerataan penuh berbiaya ${(a0(1000).cov-a1(1000).cov).toFixed(1)} poin cakupan nasional untuk ${(a0(1000).gini-a1(1000).gini).toFixed(2)} poin Gini.</li>
  <li><b>Kesetaraan per kapita, ekuitas bagi termiskin, dan efisiensi cakupan adalah tiga tujuan berbeda</b> dengan penerima berbeda (Bogor/Malang vs Papua/NTT vs Kalimantan luas); setelah ±500 situs ketiganya tidak bisa dimaksimalkan bersama — riset ini harus menyatakan fungsi tujuannya, dan rekomendasi yang dipertahankan adalah campuran 50/50 dengan tiga ukuran dilaporkan bersama.</li></ol>`;
 $('kdLimit').innerHTML+=` <b>Lanjutan (§6–§8, <code>equitymap/dinamika.py</code>):</b> bobot spasial = ketetanggaan poligon geoBoundaries ADM2 (buffer ±0,5 km; ${M.n_island} pulau tanpa tetangga memakai 3 centroid terdekat; rata-rata ${M.deg_mean} tetangga), Moran's I dan LISA dengan ${M.perms} permutasi (LISA: permutasi kondisional dengan pengembalian), variabel log(1+charger/100 rb); deret waktu Jawa Barat dari tanggal operasi nyata, nasional dari kalibrasi ID (akurasi ${CB.acc}%); skenario water-filling = tiap kabupaten diangkat ke ambang per kapita t (tanpa mengurangi yang di atas), biaya = asumsi slider; simulasi campuran menempatkan ${M.ch_site} charger per situs baru, aturan pemerataan memilih kabupaten dengan charger/kapita terendah lalu heksagon dengan penduduk belum tercakup terbanyak di dalamnya, aturan cakupan = greedy maximum coverage radius ≈10 km; tidak ada batasan jaringan listrik, lahan, atau permintaan dalam simulasi.`;
};
})();
